app_group:
  - read:
      path: /apps/vmware.eda.nokia.com
      method: GET

intent_targets:
  - read:
      path: /apps/vmware.eda.nokia.com/v1/vmwareplugininstances/{name}/_targets
      method: GET

k8_s_topology_request:
  - create:
      path: /apps/vmware.eda.nokia.com/v1/vmwareplugininstances/{name}/_topology
      method: POST

resource_history:
  - read:
      path: /apps/vmware.eda.nokia.com/v1/vmwareplugininstances/{name}/_revs
      method: GET

resource_list:
  - read:
      path: /apps/vmware.eda.nokia.com/v1
      method: GET

resource_topology:
  - read:
      path: /apps/vmware.eda.nokia.com/v1/vmwareplugininstances/{name}/_topology
      method: GET

status:
  - delete:
      path: /apps/vmware.eda.nokia.com/v1/vmwareplugininstances/{name}
      method: DELETE

ui_result:
  - read:
      path: /apps/vmware.eda.nokia.com/v1/_ui/{pathname}
      method: GET

com.nokia.eda.vmware.v1.vmware_plugin_instance:
  - create:
      path: /apps/vmware.eda.nokia.com/v1/vmwareplugininstances
      method: POST
  - read:
      path: /apps/vmware.eda.nokia.com/v1/vmwareplugininstances/{name}
      method: GET
  - update:
      path: /apps/vmware.eda.nokia.com/v1/vmwareplugininstances/{name}
      method: PUT
  - update:
      path: /apps/vmware.eda.nokia.com/v1/vmwareplugininstances/{name}
      method: PATCH

com.nokia.eda.vmware.v1.vmware_plugin_instance_list:
  - read:
      path: /apps/vmware.eda.nokia.com/v1/vmwareplugininstances
      method: GET
  - delete:
      path: /apps/vmware.eda.nokia.com/v1/vmwareplugininstances
      method: DELETE

com.nokia.eda.vmware.v1.vmware_plugin_instance_deleted_resources:
  - read:
      path: /apps/vmware.eda.nokia.com/v1/vmwareplugininstances/_deleted
      method: GET

totalPaths: 9
totalSchemas: 54
usedSchemas: 11
unusedSchemas: 43
unusedSchemaList:
  - AppGroupVersion
  - ErrorIndex
  - ErrorItem
  - ErrorResponse
  - IntentTarget
  - K8SPatchOp
  - OverlayState
  - Patch
  - Resource
  - ResourceHistoryEntry
  - StatusDetails
  - TopoAttrMetadata
  - TopoAttribute
  - TopoBoolExpression
  - TopoBoolLiteral
  - TopoElemMetadata
  - TopoEndpointBoolExpression
  - TopoField
  - TopoFixedBoolExpression
  - TopoLabelSelector
  - TopoLiteralStatusOrBadge
  - TopoLiteralValue
  - TopoLogicalExpression
  - TopoNodeGrouping
  - TopoOverlayEndpoint
  - TopoOverlayEndpointState
  - TopoOverlayLink
  - TopoOverlayLinkGroup
  - TopoOverlayLinkGroupEndpoint
  - TopoOverlayLinkState
  - TopoOverlayNode
  - TopoOverlayNodeOrGroup
  - TopoOverlayNodeState
  - TopoOverlayValue
  - TopoSchema
  - TopoStateFilter
  - TopoValue
  - TopoValueExpression
  - Topology
  - com.nokia.eda.vmware.v1.VmwarePluginInstance_DeletedResourceEntry
  - com.nokia.eda.vmware.v1.VmwarePluginInstance_alarms
  - com.nokia.eda.vmware.v1.VmwarePluginInstance_deviations
  - com.nokia.eda.vmware.v1.VmwarePluginInstance_metadata
